---
# This file is part of Ansible role geoffreyvanwyk.php.
#
# Ansible role geoffreyvanwyk.php is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.php is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.php. If not, see <https://www.gnu.org/licenses/>.

##
# Variable values different from the defaults; also, required variables without
# default values.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
# @see        The Scenario Layout (https://ansible.readthedocs.io/projects/molecule/getting-started/#the-scenario-layout)
##

php_version: 8.0
php_mod_enabled:
  - intl
  - mysqli
  - xml
  - fpm
php_mod_disabled:
  - shmop
  - sockets
  - iconv
php_ini_cli:
  - name: allow_url_fopen
    value: "Off"
  - name: memory_limit
    value: -1
  - name: date.timezone
    value: "Africa/Johannesburg"
php_ini_apache:
  - name: post_max_size
    value: 127M
  - name: upload_max_filesize
    value: 33M
  - name: max_file_uploads
    value: 13
php_ini_fpm:
  - name: max_execution_time
    value: 300
  - name: max_input_time
    value: 600
  - name: max_input_vars
    value: 5000
