---
# This file is part of Ansible role geoffreyvanwyk.php.
#
# Ansible role geoffreyvanwyk.php is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.php is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.php. If not, see <https://www.gnu.org/licenses/>.

##
 # Contains the call to the role when testing with Molecule.
 #
 # @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
 # @see        The Scenario Layout (https://ansible.readthedocs.io/projects/molecule/getting-started/#the-scenario-layout)
##

- name: Converge for PHP 8.0
  ansible.builtin.import_playbook: ./converge_php_80.yml

- name: Converge for PHP 8.2
  ansible.builtin.import_playbook: ./converge_php_82.yml
