---
# This file is part of Ansible role geoffreyvanwyk.php.
#
# Ansible role geoffreyvanwyk.php is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.php is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.php. If not, see <https://www.gnu.org/licenses/>.

##
 # Entry point for all tasks performed by the role.
 #
 # @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Install dependency for apt_repository module - dirmngr
  # apt_repository depends on gnupg which in turn depends on dirmngr
  ansible.builtin.apt:
    package:
      - dirmngr
    state: present

- name: Add package repository for PHP versions
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP
  ansible.builtin.apt:
    package:
      - php{{ php_version }}
    state: present

- name: Install PHP modules that should be enabled
  loop: "{{ php_mod_enabled }}"
  ansible.builtin.apt:
    package: php{{ php_version }}-{{ item }}
    state: present

- name: List enabled PHP modules
  ansible.builtin.command:
    cmd: php{{ php_version }} -m
  changed_when: false
  register: php_modules

- name: Enable PHP modules
  loop: "{{ php_mod_enabled }}"
  ansible.builtin.command:
    cmd: phpenmod -v {{ php_version }} {{ item }}
  changed_when: item not in php_modules.stdout_lines

- name: Disable PHP modules
  loop: "{{ php_mod_disabled }}"
  ansible.builtin.command:
    cmd: phpdismod -v {{ php_version }} {{ item }}
  changed_when: item in php_modules.stdout_lines
