---
# This file is part of Ansible role geoffreyvanwyk.php.
#
# Ansible role geoffreyvanwyk.php is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.php is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.php. If not, see <https://www.gnu.org/licenses/>.

##
 # Contains specific tests against the state of the container after the role has
 # finished executing.
 #
 # @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
 # @see        The Scenario Layout (https://ansible.readthedocs.io/projects/molecule/getting-started/#the-scenario-layout)
##

- name: Verify
  hosts: all
  gather_facts: false

  vars_files:
    - ../../defaults/main.yml
    - vars/main.yml

  tasks:
    - name: Confirm PHP is installed
      ansible.builtin.command:
        cmd: php{{ php_version }} --version
      changed_when: false

    - name: List enabled PHP modules
      ansible.builtin.command:
        cmd: php{{ php_version }} -m
      changed_when: false
      register: php_modules

    - name: Confirm enabled PHP modules
      loop: "{{ php_mod_enabled }}"
      ansible.builtin.assert:
        that: "{{ item in php_modules.stdout_lines }}"

    - name: Confirm disabled PHP modules
      loop: "{{ php_mod_disabled }}"
      ansible.builtin.assert:
        that: "{{ not item in php_modules.stdout_lines }}"

    - name: Confirm initialization values - CLI
      loop: "{{ php_ini_cli }}"
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: set -o pipefail && php{{ php_version }} -i | grep -P '^{{ item.name }} *=>.*=> *{{ item.value }}'
      changed_when: false

    - name: Display PHP info for Apache
      when: php_ini_apache | length > 0
      ansible.builtin.uri:
        url: http://localhost/phpinfo.php
        return_content: true
      register: php_info_apache

    - name: Confirm initialization values - Apache
      loop: "{{ php_ini_apache }}"
      ansible.builtin.assert:
        that: "{{ php_info_apache.content
          | regex_findall('<tr><td class=\"e\">' + item.name + '</td><td class=\"v\">' + (item.value | string))
          | list
          | length > 0 }}"

    - name: Confirm initialization values - FPM
      loop: "{{ php_ini_fpm }}"
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: set -o pipefail && php-fpm{{ php_version }} -tt | grep -P '{{ item.name }} = {{ item.value }}'
      changed_when: false
